//
// MYbloXX by MYXXdev (Default)
// Updated: 10/21/23 - 06:22 MST
// Support Development: MYXXfm.com/donate
//
const MYBLOXX = "PROXY 127.0.0.1:8021";
const ALLOW = "DIRECT";
const BYPASS = "PROXY 8.8.8.8:53";

function testMatchesHostsOrShUrlRegexes(url, host, matchingHosts, matchingShUrlRegexes) {
    let i;
    for(i = 0; i < matchingHosts.length; ++i) {
        if(dnsDomainIs(host, matchingHosts[i])) {
            return true;
        }
    }
    for(i = 0; i < matchingShUrlRegexes.length; ++i) {
        if(shExpMatch(url, matchingShUrlRegexes[i])) {
            return true;
        }
    }
    return false;
}

function FindProxyForURL(url, host) {
    url = url.toLowerCase();
    host = host.toLowerCase();
    
    const allowedHosts = [];
    const allowedShUrlRegexes = [
        '*adblock-tester*', '*adsbe*', '*adsl*', '*adverts.ie*', '*ai.marketing*', '*analytics.twitter*', '*api.ay.gy*',
        '*api.push.*', '*app.adjust*', '*banner.tw*', '*bannerweb.*', '*beatmarketing*', '*bnbstatic*',
        '*bostadsbolaget*', '*castrads*', '*cdn-marketing*', '*cdn.jsdelivr*', '*checkadblock*',
        '*conversions.appsflyer*', '*countervalues.live*', '*cuetracker.net*', '*dead*', '*deembesign.club*',
        '*gumtree*', '*gungho*', '*heads*', '*hulustream*', '*jsmu.edu*', '*kinja-static*', '*loads*', '*lpsnmedia*',
        '*marketing.lyft*', '*marketing.zobj*', '*marketingcloud*', '*ms-com*', '*old.reddit.com*', '*promo.api*',
        '*propellerhealth*', '*reads*', '*roads*', '*rotherhamad*', '*salads*', '*sentry-read*', '*simplex-aff*',
        '*sponsor.ajay*', '*ssb-banner.humber*', '*starad*', '*swindonad*', '*ulink.adjust*', '*universaltennis*',
        '*universaltruthschool*', '*unsub*', '*wadsw*', '*washingtonexaminer*', '*yieldwatch*'
    ];
    
    const bypassUrlHosts = [];
    const bypassShUrlRegexes = [
        '*adsafeprotected*', '*app-analytics*', '*app-measurement*', '*applovin*', '*googlead*', '*googlesyndication*',
        '*googletag*'
    ];
    
    const blockedHosts = [
        '0pixl.com', '100widgets.com', '11bet.net', '156th.com', '1rx.io', '1rxntv.io', '2020mustang.com',
        '20dollars2surf.com', '21sexturycash.com', '247teencash.net', '24hrnewszone.com', '24hstatic.com',
        '24smile.org', '254a.com', '2giga.download', '2mdn.net', '2o7.net', '3file.info', '3gporn.biz', '3lift.com',
        '42trck.com', '4spoonyexperiment.com', '4wnet.com', '88-f.net', '888media.net', '8live.com', '9content.com',
        'a-mo.net', 'a-static.com', 'a.ki', 'a.livesportmedia.eu', 'a.pr-cy.ru', 'a3.hotpornfile.org',
        'aaadealstoday.com', 'aan.amazon.com', 'aax-eu-dub.amazon.com', 'aax-us-iad.amazon.com', 'abakus.freenet.de',
        'abakys.ru', 'abctrack.bid', 'acacdn.com', 'acales.ru', 'accordprybreathe.com', 'accounts.pkr.com',
        'acdcdn.com', 'acertb.com', 'acidpigs.com', 'acloudimages.com', 'acloudvideos.com', 'acount.alley.ws',
        'actuallysheep.com', 'acuityplatform.com', 'ad-balancer.net', 'ad-delivery.net', 'ad-maven.com', 'ad.daum.net',
        'ad.gt', 'ad.mail.ru', 'ad.style', 'ad131m.com', 'ad1data.com', 'ad1rtb.com', 'ad4980.kr', 'ad4game.com',
        'ad5lm.net', 'ad6media.fr', 'ad7.com', 'adalliance.io', 'adalyser.com', 'adamatic.co', 'adap.tv', 'adapd.com',
        'adaranth.com', 'adb.fling.com', 'adbetclickin.pink', 'adbetnet.com', 'adbidgo.com', 'adblade.com', 'adbma.com',
        'adbooth.com', 'adbox.lv', 'adbureau.net', 'adca.st', 'adcamel.pw', 'adcash.com', 'adcde.com', 'adcdnx.com',
        'adchemy-content.com', 'adclear.net', 'addthis.com', 'addtoany.com', 'adearsened.info', 'adex.media',
        'adexc.net', 'adform.net', 'adfox.yandex.ru', 'adfoz.com', 'adfpoint.com', 'adframesrc.com',
        'adfrastingathles.info', 'adfusion.com', 'adgear.com', 'adgebra.in', 'adgeiros.pw', 'adgitize.com',
        'adhacker.online', 'adhealers.com', 'adhits.cf', 'adhoc2.net', 'adhome.biz', 'adhood.com', 'adigniter.org',
        'adingo.jp', 'adintend.com', 'adinterax.com', 'adip.ly', 'adiquity.com', 'adition.com', 'adjust.com', 'adku.co',
        'adlayer.net', 'adlightning.com', 'adlink.net', 'adloop.co', 'adlure.net', 'adm.shinobi.jp', 'admanmedia.com',
        'admaya.in', 'admaza.in', 'admedit.net', 'admeerkat.com', 'admicro.vn', 'adminpromotion.com', 'admission.net',
        'admitad.com', 'admixer.net', 'admjmp.com', 'admngronline.com', 'admost.com', 'adn.ebay.com', 'adnext.fr',
        'adnigma.com', 'adnium.com', 'adnmn.com', 'adnxs.com', 'adnz.co', 'adocean.pl', 'adofqudjesh.com', 'adonweb.ru',
        'adop.cc', 'adoperatorx.com', 'adopexchange.com', 'adopshost.me', 'adotube.com', 'adpass.co.uk', 'adpatrof.com',
        'adplexo.com', 'adplusplus.fr', 'adplxmd.com', 'adpone.com', 'adport.io', 'adpushup.com', 'adquality.ch',
        'adreach.me', 'adreactor.com', 'adreadytractions.com', 'adrevolver.com', 'adright.co', 'adro.co', 'adrta.com',
        'adrunnr.com', 'adtarget.me', 'adtelligent.com', 'adtgs.com', 'adtimaserver.vn', 'adtiming.com', 'adtng.com',
        'adtotal.pl', 'adtrace.org', 'adtrue.com', 'adultadworld.com', 'adultblogtoplist.com', 'adultcommercial.net',
        'adultimate.net', 'adultmoda.com', 'adultsense.org', 'adultterritory.net', 'adv.ettoday.net',
        'adv.insegreto.com', 'advangelists.com', 'adverkeyz.com', 'adverserve.net', 'advise.co', 'advmaiotg.com',
        'advmedialtd.com', 'adwalte.info', 'adx.com.ru', 'adxite.com', 'adxpansion.com', 'adxpremium.services',
        'adxprtz.com', 'adyoulike.com', 'adz.co.zw', 'adzfun.me', 'adziff.com', 'adzincome.in', 'adzintext.com',
        'adzmaza.in', 'aemediatraffic.com', 'aeros02.tk', 'aeros08.tk', 'afclickoffers.com', 'afcontent.net',
        'afcpatrk.com', 'aff.biz', 'affec.tv', 'affiliaxe.com', 'affiligay.net', 'affilijack.de', 'affiliproducts.com',
        'affiliserve.com', 'affilizr.com', 'affportal-lb.bevomedia.com', 'afftrack.com', 'aflemy.com', 'agkn.com',
        'aicontents.net', 'aio.media', 'airpushmarketing.s3.amazonaws.com', 'ajplugins.com', 'alchemysocial.com',
        'alcnpm.com', 'algocashmaster.net', 'ali-crm.ru', 'alibestru.ru', 'alladultcash.com', 'allbestsecureus.com',
        'allhottoss.cam', 'alma-cmp.almamedia.io', 'aloguerequi.space', 'alxsite.com', 'am10.ru', 'am11.ru', 'am15.net',
        'amateurcouplewebcam.com', 'amazon-cornerstone.com', 'amazonclix.com', 'ambient-platform.com',
        'ambientplatform.vn', 'americanconsumernews.net', 'amgdgt.com', 'amgload.net', 'amobee.com', 'ampxchange.com',
        'amung.us', 'an.facebook.com', 'an.yandex.ru', 'analitycs.net', 'analysis.fi', 'analysis.shinobi.jp',
        'andbeyond.media', 'andomedia.com', 'andomediagroup.com', 'aniview.com', 'annabelleabe.com', 'announcement.ru',
        'antdivisitlodg.info', 'anti-bot.baidu.com', 'anymedia.lv', 'api.facebook.com', 'apkonline.ru',
        'app.chat.xiaomi.net', 'appbaqend.com', 'appboy.com', 'apple.comscoreresearch.com', 'applovefrom.com',
        'applvn.com', 'appmessages.com', 'appodeal.com', 'appota.com', 'apprupt.com', 'appsflyer.com',
        'arapidlearn.biz', 'areadonna.com', 'armhutspa.com', 'armiesgiddinesscanes.com',
        'artisticdisgraceevidently.com', 'asdasdad.net', 'asp.animelab.com', 'astancerta.fun', 'asterpix.com',
        'atanx.alicdn.com', 'athenainstitute.biz', 'athenatmpbeacon.theglobeandmail.ca', 'athfieldmast.club',
        'atlas.astrology.com', 'atsptp.com', 'attributiontrackingga.googlecode.com', 'atwola.com',
        'audience-mostread.r7.com', 'audienceprofiler.com', 'august15download.com', 'aulteeby.net', 'avaniolabs.com',
        'avct.cloud', 'avocet.io', 'awebotchunto.work', 'awelessawelesscedar.com', 'awemdia.com', 'aweprotostatic.com',
        'aweprt.com', 'aweptjmp.com', 'awestatic.com', 'awfulporetroys.casa', 'awstaticdn.net', 'ay.gy', 'aztecash.com',
        'b.gemini.yahoo.com', 'b1img.com', 'b72.info', 'badge.facebook.com', 'balebunsob.com', 'baleiambwee.com',
        'banesnorttat.cam', 'baresi.xyz', 'barscreative1.com', 'bat.adforum.com', 'bat.bing.com',
        'bats.video.yahoo.com', 'bdstatic.com', 'beacon.examiner.com', 'beacon.sojern.com', 'beacons.mediamelon.com',
        'beap-bc.yahoo.com', 'beap.gemini.yahoo.com', 'bebi.com', 'bedrapiona.com', 'beead.net', 'belamicash.com',
        'beleiambwee.com', 'bellatraffic.com', 'bepiletussar.casa', 'bestaryua.com', 'bestbulking.com',
        'bestcontentfood.top', 'bestdeal2060.info', 'bestdeals.ws', 'bestdisplayformats.com', 'bestforexplmdb.com',
        'bestprizeday.life', 'bestquickcontentfiles.com', 'betahit.click', 'betrad.com', 'bettingpartners.com',
        'betweendigital.com', 'bfast.com', 'bid.glass', 'bidfilter.com', 'bidgear.com', 'bidiology.com',
        'bidmachine.io', 'bidsxchange.com', 'bidvertiser.com', 'bighot.ru', 'bilsyndication.com', 'bilugo.com',
        'bin-layer.ru', 'binary1.website', 'birthdiscipline.com', 'bisko.mall.tv', 'bitx.tv', 'bizible.net',
        'bizibly.com', 'bkrtx.com', 'blaaaa12.googlecode.com', 'blockscoolest.com', 'bloggerex.com',
        'bloggergreetbox.googlecode.com', 'bloglife24.com', 'bloglines.com', 'bloodhound.spotify.com', 'bluekai.com',
        'blueparrot.media', 'bmfeed.ru', 'bnserving.com', 'bo-videos.s3.amazonaws.com', 'board-books.com', 'bodis.com',
        'boinkcash.com', 'boomtrain.com', 'bootstraplugin.com', 'botdetector.ru', 'botscanner.com', 'botsvisit.com',
        'bounceexchange.com', 'bowmoolog.com', 'brainian.club', 'branch.io', 'brand-display.com', 'brand.net',
        'brandaffinity.net', 'brandlock.io', 'brandreachsys.com', 'braze.com', 'breakfastboat.com', 'brid.tv',
        'brinkstretching.com', 'broaddoor.com', 'brothersincash.com', 'browser-updater.yandex.net', 'browsiprod.com',
        'brushdaughter.com', 'btbuckets.com', 'btn.clickability.com', 'btstatic.com', 'bubblyalibiappear.com',
        'budapebluest.com', 'bumblecash.com', 'bureaucracycrutch.com', 'busilyrecordingto.com', 'buythis.ad',
        'byteoversea.com', 'bzclk.baidu.com', 'c.imedia.cz', 'c1exchange.com', 'c2shb.ssp.yahoo.com',
        'c4tracking01.com', 'cacafly.net', 'cadreon.s3.amazonaws.com', 'caiteesh.net', 'cam-lolita.net', 'cam4flat.com',
        'camakaroda.com', 'camcrush.com', 'camdough.com', 'camduty.com', 'cameraprive.com', 'camiocw.com',
        'campanja.com', 'campartner.com', 'camprime.com', 'campromos.nl', 'cams.enjoy.be', 'camsense.com',
        'camsoda1.com', 'camzap.com', 'cantholdus.xyz', 'carousel.dcard.tw', 'carray-visher.com', 'carscannon.com',
        'cas.clickability.com', 'casalemedia.com', 'cash-duck.com', 'cash-program.com', 'cash.femjoy.com',
        'cash4members.com', 'cashbigo.com', 'cashburners.com', 'cashcave.net', 'cashlayer.com', 'cashmylinks.com',
        'cashthat.com', 'cashworld.biz', 'casinohacksforyou.com', 'castplatform.com', 'cavewaxmalt.com',
        'cb-content.com', 'cbs.wondershare.com', 'ccexperimentsstatic.oracleoutsourcing.com',
        'ccpa-script.psg.nexstardigital.net', 'cdn-alliancegravity.s3.amazonaws.com', 'cdn-code.host', 'cdn.asf4f.us',
        'cdn.assets.gorillanation.com', 'cdn.hiido.cn', 'cdn.mobicow.com', 'cdn.offcloud.com', 'cdn.optmd.com',
        'cdn.trafficexchangelist.com', 'cdn777.net', 'cdnaz.win', 'cdncache2-a.akamaihd.net', 'cdnmaster.cn',
        'cdnmaster.com', 'cdnmr.net', 'cdnondemand.org', 'cdnproviders.net', 'cepractliq.top', 'cetlog.jp', 'cf-se.com',
        'chameleon.ad', 'chargeplatform.com', 'chartaca.com', 'chasteminihaunting.com', 'chatango.com', 'checkmy.cam',
        'checkoutfree.com', 'checkstat.nl', 'cheqzone.com', 'christianris.com', 'circumscribevetofurther.com',
        'circumstantialobtrusive.com', 'class2deal.com', 'class64deal.com', 'clck.yandex.com', 'clck.yandex.ru',
        'clean.gg', 'clearbit.com', 'clearbriefing.xyz', 'clickaine.com', 'clickcdn.co', 'clickco.net',
        'clickdimensions.com', 'clickfuse.com', 'clickguardian.app', 'clicki.cn', 'clickitover.com', 'clickmap.ch',
        'clickmngr.com', 'clickosmedia.com', 'clickpathmedia.com', 'clickperks.info', 'clickppcbuzz.com',
        'clicks.hurriyet.com.tr', 'clicksgear.com', 'clickstream.co.za', 'clicksvenue.com', 'clickthru.lefbc.com',
        'clickz.lonelycheatingwives.com', 'clksite.com', 'clmbtech.com', 'cloudcdn.gdn', 'cloudcoins.co',
        'cloudfrale.com', 'cloudfront-labs.amazonaws.com', 'cloudgallery.net', 'cloudimagesa.com', 'cloudmobi.net',
        'cloudvideosa.com', 'club.org', 'cluep.com', 'cluodlfare.com', 'cmp.channelpartner.de', 'cmp.nextday.media',
        'cmstool.youku.com', 'codedexchange.com', 'codedpigzed.com', 'cogleapad.com', 'cogmatch.net',
        'cognitivematch.com', 'coinmedia.co', 'cokhach.com', 'coldhardcash.com', 'collecting.click', 'comasoiling.casa',
        'comet.yahoo.com', 'cometmaster.com', 'comfortlesswastefulcinnamon.com', 'commercialvalue.org',
        'complexmedianetwork.com', 'comscore.com', 'conditionstray.com', 'confiant.msn.com', 'connatix.com',
        'connect.ok.ru', 'connection-patrix.com', 'connexplace.com', 'contactmonkey.com', 'contadordevisitas.es',
        'contadorvisitasgratis.com', 'content-cooperation.com', 'content-recommendation.net', 'content-square.net',
        'content.ad', 'content.livesportmedia.eu', 'content.liveuniverse.com', 'content.secondspace.com',
        'contentabc.com', 'contentcache-a.akamaihd.net', 'contentdigital.info', 'contentexchange.me',
        'contentinsights.com', 'contentjs.com', 'contentr.net', 'contentsfeed.com', 'contentspread.net',
        'contentsquare.net', 'contenture.com', 'contentwidgets.net', 'contribusourcesyndication.com',
        'conversions.genieventures.co.uk', 'convertexperiments.com', 'convertsocial.com', 'convrse.media', 'cooch.tv',
        'cookie.gazeta.pl', 'cookie.support', 'cookiebot.com', 'cookiechoices.org', 'cookiefirst.com', 'cookielaw.org',
        'cookiemanager1.contentforces.com', 'cookiemonster.is', 'cookierulez.sqrt64.it', 'cookies.forbes.pl',
        'cookies.reedbusiness.nl', 'cookiex.ngd.yahoo.com', 'cootlogix.com', 'core.queerclick.com',
        'count5.pconline.com.cn', 'countus.fr', 'couponcashmerelining.com', 'cpalabtracking.com', 'cpalead.com',
        'cpl1.ru', 'cpm.biz', 'cpmstar.com', 'cpu2cash.link', 'cpx.to', 'cr-brands.net', 'cr-nielsen.com',
        'crakcash.com', 'creamssicsite.com', 'creativecdn.com', 'creepingbrings.com', 'crosspixel.net',
        'crueltyrefundye.com', 'crwdcntrl.net', 'csc.beap.bc.yahoo.com', 'csi.gstatic.com', 'cstraffic.com',
        'cstwpush.com', 'cszz.ru', 'ct.pinterest.com', 'cthorrowu.club', 'cunugysy.pro', 'd.adrolays.de', 'd0main.ru',
        'dable.io', 'dabong247.com', 'dad-api.dcard.tw', 'dailycaller-alerts.com', 'danzabucks.com', 'dareboost.com',
        'dashbida.com', 'dashboard.io', 'dashboardad.net', 'data-data-vac.com', 'data.glamour.ru', 'data.imakenews.com',
        'data.minute.ly', 'data.neuroxmedia.com', 'data.queryly.com', 'data.studybreakmedia.com418', 'data.younow.com',
        'databerries.com', 'datadome.co', 'datafront.co', 'datefree.com', 'datexchanges.net', 'dating2cloud.org',
        'dauup.com', 'dawin.tv', 'dditscdn.com', 'dealcurrent.com', 'dealspure.com', 'deecash.com',
        'definitetransfer.com', 'delightfulold.com', 'deliv.lexpress.fr', 'demandmedia.s3.amazonaws.com',
        'denetsuk.com', 'designergumsobituary.com', 'despisenoughtshit.com', 'destore-daindmade.com',
        'developermedia.com', 'deviouscoupbrutally.com', 'devscroll.com', 'dexchangegenius.com', 'dexplatform.com',
        'dexpredict.com', 'dgtnoyoud.com', 'diagnose.igstatic.com', 'digiad.co', 'digitalcertvalidation.co',
        'digitaltarget.ru', 'directchat.tv', 'directcrm.ru', 'directtrack.com', 'displayvertising.com', 'dispop.com',
        'distinctionlatent.com', 'districtm.io', 'divascam.com', 'dl.meliacloud.com', 'dmclick.cn', 'dochase.com',
        'dollarade.com', 'dolohen.com', 'dortoolr.com', 'dosugcz.biz', 'dot-stat.radikal.ru', 'dotandad.com',
        'dotnetkicks.com', 'doublepimp.com', 'douhooke.net', 'download-performance.com',
        'downloadandsave-a.akamaihd.net', 'downloadboutique.com', 'drawbacksubdue.com', 'drift.com', 'drivenetwork.ru',
        'drizly.com', 'dropzenad.com', 'drowadri.racing', 'dryone-incess.com', 'dtscout.com', 'ducationalco.biz',
        'dumbpop.com', 'dumdex.net', 'dumpersgoofed.com', 'dup.baidustatic.com', 'dwin2.com', 'dyn.primecdn.net',
        'dynad.net', 'dz4ad.com', 'dzizsih.ru', 'e-contenta.com', 'e-kuzbass.ru', 'easy-bars.com',
        'ebayclassifiedsgroup.com', 'ebayobjects.com.au', 'eclick.baidu.com', 'eclick.vn', 'ecomm.events',
        'ecsqyotk.com', 'edilparati3000.it', 'eelsouph.click', 'eg-p2.eurogamer.net', 'egamiplatform.tv',
        'eggsosgum.site', 'eikegolehem.com', 'electricalbicyclelistnonfiction.com', 'elefantsearch.com',
        'elessecsta.top', 'elevenmedia.cn', 'email-match.com', 'embedstream.me', 'empiremoney.com',
        'engage-cdn.schibsted.media', 'enginsquawks.cam', 'entrecard.s3.amazonaws.com', 'entrepreneur.com',
        'epacash.com', 'epeex.io', 'epnt.ebay.com', 'epowernetworktrackerimages.s3.amazonaws.com', 'epu.sh',
        'eredexpendin.com', 'ereenerall.fun', 'erevtljvo.com', 'escape.insites.eu', 'estat.com', 'esusivebe.top',
        'et-code.ru', 'etahub.com', 'etology.com', 'etzbnfuigipwvs.ru', 'eulerian.brandalley.fr',
        'eurogamer-uk.eurogamer.net', 'europacash.com', 'event-api.contactatonce.com', 'eventgateway.soundcloud.com',
        'events.api.godaddy.com', 'events.avantisvideo.com', 'events.redditmedia.com', 'events.tubecup.org',
        'eventtracker.videostrip.com', 'everesttech.net', 'evergreensame.com', 'evidon.com', 'evisit.exeter.ac.uk',
        'exchangecash.de', 'exdynsrv.com', 'exelator.com', 'exitexplosion.com', 'exovueplatform.com', 'expdb2.msn.com',
        'experianmarketingservices.digital', 'explore-123.com', 'expmediadirect.com', 'expocrack.com', 'expogrim.com',
        'exponea.com', 'exponential.com', 'exposebox.com', 'extend.tv', 'extmaps-api.yandex.net',
        'extreme-ip-lookup.com', 'eyeota.net', 'eyereturn.com', 'eyewonder.com', 'ezdownloadpro.info', 'ezimar.com',
        'ezodn.com', 'ezytrack.com', 'f.staticlp.com', 'facebookicon.net', 'faceearlobe.com', 'faigroas.net',
        'fandelcot.com', 'fanplayr.com', 'fansign.streamray.com', 'farehitchlower.icu', 'fashionnightingale.com',
        'fast-thinking.co.uk', 'fast2earn.com', 'fasta.xyz', 'fastapi.net', 'fastonlineusers.com', 'faststart.ru',
        'fatchilli.media', 'fathom.status.im', 'fbpopr.com', 'fc.yahoo.com', 'fiefionfortes.casa', 'fileloadr.com',
        'filetarget.com', 'filetarget.net', 'filexan.com', 'fimg-resp.seznam.cz', 'finance-reporting.org',
        'find-ip-address.org', 'firebaselogging.googleapis.com', 'firescorrelationprodigy.com', 'fireworktv.com',
        'firstclass-download.com', 'firstload.de', 'five88.com', 'fivecdm.com', 'fkrkkmxsqeb5bj9r.s3.amazonaws.com',
        'flagship.asp-host.co.uk', 'flashadengine.com', 'flashgroup.com', 'flashtalking.com', 'fleshcash.com',
        'flingywalkup.com', 'flixsyndication.net', 'fluentmobile.com', 'fluffyeaster.com', 'flurry.com', 'fmscash.com',
        'fncash.com', 'fog.pixual.co', 'followistic.com', 'forlumineoner.com', 'forter.com', 'forttantontherdown.info',
        'found.ee', 'fout.jp', 'fpa-events.arstechnica.com', 'fpctraffic2.com', 'fpctraffic3.com',
        'fractionalmedia.com', 'freakspybad.com', 'free-debride.id.st', 'free-domain.net', 'freecouponbiz.com',
        'freeevpn.info', 'freegamespub.com', 'freeonlineusers.com', 'freerotator.com', 'freeskreen.com',
        'freesoftwarelive.com', 'freestar.io', 'freetellafriend.com', 'freetrafficsystem.com', 'freeusenet.rocks',
        'freeusersonline.com', 'freewebfonts.org', 'freychang.fun', 'fuck-journey.com', 'fuelbuck.com', 'fullstory.com',
        'fundingchoicesmessages.google.com', 'future-hawk-content.co.uk', 'fwmrm.net', 'fwpixel.com', 'fykmahfa.com',
        'g-cash.biz', 'g.msn.com', 'g.yccdn.com', 'g2afse.com', 'gainmoneyfast.com', 'gainoverprotective.com',
        'galaks.io', 'galaxiemedia.fr', 'gamecetera.com', 'gamersad.com', 'gamescarousel.com', 'gamesrevenu24.com',
        'gamesrevenue.com', 'gamevui24.com', 'gammaplatform.com', 'gandrad.org', 'ganon.yahoo.com', 'garss.tv',
        'gashot.yurivideos.com', 'gateways.s3.amazonaws.com', 'gaug.es', 'gbotvisit.com', 'gcpdata.telegraph.co.uk',
        'gdeslon.ru', 'geedoovu.net', 'geistm.com', 'gejute.com', 'gemini.yahoo.com', 'gen.etherscan.io',
        'geniusdexchange.com', 'geo.q5media.net', 'geo.query.yahoo.com', 'geo.yahoo.com', 'geofamily.ru',
        'geoplugin.net', 'getadmiral.com', 'getalinkandshare.com', 'getclicky.com', 'getcontent.net', 'getfreebl.com',
        'getgamers.eu', 'getpushmonkey.com', 'getscriptjs.com', 'getsitecontrol.com', 'getsmartcontent.com',
        'ggwcash.com', 'gl-cash.com', 'global.com', 'global-support.report', 'global-support.store',
        'global-surveys.co', 'globaltraffico.com', 'glotchat.click', 'gmonitor.aliimg.com', 'gmzdaily.com', 'gnezdo.ru',
        'go-rillatrack.com', 'go2s.co', 'goingsilltrusty.com', 'gourair.xyz', 'govid.co', 'goviral-content.com',
        'graizoah.com', 'graniteacquitcharacteristic.com', 'graph.facebook.com', 'graph.instagram.com', 'gravatar.com',
        'greatdexchange.com', 'greemeek.net', 'greystripe.com', 'gripdownload.co', 'grooksom.com', 'group-ib.ru',
        'gsp1.baidu.com', 'gtrk.s3.amazonaws.com', 'guffawdecipher.com', 'gulliblecamp.com', 'gumgum.com', 'gus.host',
        'gvisit.com', 'h.imedia.cz', 'haloscan.com', 'hashforcash.us', 'hashing.win', 'hastopnet.com',
        'hbid.ams3.cdn.digitaloceanspaces.com', 'headquartercloudlessselfservice.com', 'hemnes.win',
        'hereditaryductserum.com', 'herofandhist.info', 'heroismyouroutnumber.com', 'hiddenbucks.com', 'hitbox.com',
        'hitcount.dk', 'hitmir.ru', 'hm.baidu.com', 'hmongcash.com', 'holmesmind.com', 'hookupbucks.com',
        'hop.clickbank.net', 'hornsbundlebetter.com', 'hornymatches.com', 'hostave3.net', 'hostcontent.live',
        'hostingcloud.racing', 'hotsocials.com', 'hotwords.com', 'hovermountedsulphur.com', 'hoverr.media', 'htl.bid',
        'humanclick.com', 'hurchaseeffectionpe.info', 'hydracdn.network', 'hyperboardupil.info', 'hypermusk.com',
        'hyperoi.com', 'i4track.net', 'iadctest.qwapi.com', 'ibillboard.com', 'icanhazip.com', 'icebns.com',
        'iclickcdn.com', 'icoawhou.com', 'icon2count.com', 'id-visitors.com', 'ideal-sexe.com', 'ideliv.net',
        'idelv.net', 'idntfy.ru', 'idolbucks.com', 'idownloadgalore.com', 'idspatchi.com', 'iesnare.com', 'ifilez.org',
        'iframe.adultfriendfinder.com', 'iframe.travel.yahoo.com', 'iframes.hustler.com', 'ifysearch.com',
        'igameunion.com', 'igaming.biz', 'igg.biz', 'iheartbucks.com', 'ihookupdaily.com', 'ikunselt.com',
        'ilovecheating.com', 'ilovejuju.be', 'im.ov.yahoo.co.jp', 'imageadvantage.net', 'images.dreamhost.com',
        'images.hitwise.co.uk', 'images.mylot.com', 'imasdk.googleapis.com', 'img.mybet.com', 'img.servint.net',
        'imgfeedget.com', 'imglt.com', 'imgpop.googlecode.com', 'imgrock.net', 'imgsniper.com', 'imgstat.baidu.com',
        'imgwebfeed.com', 'imgwzzmb.net', 'imho.ru', 'immassets.s3.amazonaws.com', 'imonomy.com', 'imp.ad-plus.cn',
        'imp.clickability.com', 'impact-ad.jp', 'impact.com', 'impactradius-event.com', 'impactserving.com',
        'impressionperformance.biz', 'imrworldwide.com', 'imspublishergroup.com', 'imstks.com', 'in-page-push.com',
        'inabsolor.com', 'incoming-data-sense360.s3.amazonaws.com', 'incompetentsummitseparation.com', 'index.ru',
        'indextools.com', 'indexww.com', 'indianlinkexchange.com', 'inewcontentdelivery.info', 'infinity-tracking.net',
        'infinity.co', 'inflationbreedinghoax.com', 'infolinks.com', 'infopicked.com', 'informvisitors.com',
        'ingenioustech.biz', 'inheart.ru', 'inmobi.com', 'inner-active.mobi', 'innovateprofit.com', 'innovid.com',
        'inpagepush.com', 'inpref.s3.amazonaws.com', 'inrd.ru', 'insideall.com', 'insightexpress.com',
        'insightexpressai.com', 'inspikon.com', 'insta-cash.net', 'instagramfollowbutton.com', 'instant.page',
        'instantdollarz.com', 'instawidget.net', 'instore.biz', 'instreamvideo.ru', 'intelensafrete.stream',
        'intelliad.de', 'intellitxt.com', 'intentarget.com', 'interakt.ru', 'intergid.ru', 'intextscript.com',
        'intimidatingclinchwily.com', 'inuxu.biz', 'investhash.com', 'investingchannel.com', 'ioam.de',
        'ioslm.haoict.co', 'iotechnologies.com', 'ip-adress.com', 'ip-api.com', 'ipdata.co', 'ipstatp.com',
        'ironbeast.io', 'ironicfolks.com', 'ironsource.mobi', 'isnssdk.com', 'itmcash.com', 'itrght.com', 'iubenda.com',
        'iwanttodeliver.com', 'javbucks.com', 'jaymancash.com', 'jewishcontentnetwork.com', 'jobsyndicate.com',
        'jobthread.com', 'join.whitegfs.com', 'joinnowinstantly.com', 'jointoyou.it', 'jomtingi.net',
        'jppolid-track.trackprod.integration.jppol.dk', 'jstracker.com', 'juicycash.net', 'jumptap.com',
        'justgetitfaster.com', 'jwpltx.com', 'kadam.ru', 'kaizenplatform.net', 'kamala-cha.com', 'kamibox.de',
        'kantarmedia.com', 'kargo.com', 'karma.mdpcdn.com', 'kaurouby.net', 'kavanga.ru', 'kbnetworkz.s3.amazonaws.com',
        'kelopronto.com', 'keyword-match.com', 'keywordpop.com', 'kikuzip.com', 'kiolim.com', 'klapenlyidveln.stream',
        'klaviyo.com', 'kmindex.ru', 'koapsooh.click', 'kodcad.kr', 'kokos.click', 'koocash.com', 'krxd.net',
        'kyvio.net', 'lacertamobile.com', 'laim.tv', 'lalaping.com', 'lavanetwork.net', 'laydata.com', 'layer-ad.org',
        'lead.im', 'leaddyno-client-images.s3.amazonaws.com', 'leadlab.click', 'leanplum.com', 'leftoverdense.com',
        'les-experts.com', 'letsgetsocialnow.com', 'lh.secure.yahoo.com', 'lifepromo.biz', 'lightingfleeventures.com',
        'lightning.cnn.com', 'lindon-pool.win', 'lineagew.plaync.com', 'lingeriebarren.com', 'link.link.ru',
        'linkexchange.com', 'linkexchangers.net', 'linkxchanger.com', 'lismcanalys.fun', 'listtop.ru', 'litix.io',
        'live.demand.supply', 'livejasmin.tv', 'livepromotools.com', 'liverail.com', 'livetex.ru', 'lixi88.info',
        'lkqd.net', 'localytics.com', 'locotrack.net', 'loerv.com', 'log.fc.yahoo.com', 'log.pinterest.com',
        'loggly.com', 'logkzudhrg.com', 'logly.co.jp', 'logql.yahoo.co.jp', 'lokvel.ru', 'lookthrilled.com',
        'louchees.net', 'louisaprocedureegoism.com', 'lovacmar.click', 'loveclaw.com', 'lovelydrum.com', 'loveme.com',
        'lovercash.com', 'lowcostinterlock.com', 'loxbeelid.com', 'lp.ncdownloader.com', 'ltassrv.com.s3.amazonaws.com',
        'lucretius-ada.com', 'lugansk-info.ru', 'luvcash.com', 'luxup.ru', 'luxup2.ru', 'm-shes.ru', 'm.yap.yahoo.com',
        'm2pub.com', 'm32.media', 'magnify360-cdn.s3.amazonaws.com', 'mailmunch.s3.amazonaws.com', 'mallorcash.com',
        'manageatea.biz', 'mangelobsolden.cam', 'marketgameframes.com', 'marketingsolutions.yahoo.com',
        'markswebcams.com', 'masoffer.net', 'mathtag.com', 'matrix-cash.com', 'maxcash.com', 'maxwellsery.com',
        'mbotvisit.com', 'mc.yandex.ru', 'mcurrentlyse.monster', 'measured.com', 'media-servers.net',
        'media.eurolive.com', 'media.match.com', 'media.mykocam.com', 'media.mykodial.com', 'media.net',
        'media.netrefer.com', 'mediamansix.com', 'mediaplex.com', 'mediaseeding.com', 'mediative.ca',
        'mediator.mail.ru', 'mediatraffic.com.ua', 'meendocash.com', 'megaad.nz', 'megadeliveryn.com',
        'memorableordealstranger.com', 'mentalks.ru', 'mentcomm.fun', 'meowpushnot.com', 'methodcash.com',
        'metric.nwsource.com', 'metricfast.com', 'metricool.com', 'metrics.icloud.com', 'metrics.mzstatic.com',
        'mfhgehrnafra.com', 'mgcash.com', 'mgcashgate.com', 'mgid.com', 'mgplatform.com', 'millioncash.ru',
        'mimgoal.com', 'min.js', 'minerad.com', 'minescripts.info', 'mintegral.com', 'mintegral.net', 'mirando.de',
        'mirtesen.ru', 'mixi.media', 'mixmarket.biz', 'mixpanel.com', 'ml314.com', 'mms.cloudpro.co.uk',
        'mnason-hec.com', 'mob-track.com', 'mobalives.com', 'mobalyzer.net', 'mobatori.com', 'mobclix.com',
        'mobday.com', 'mobdefence.com', 'mobfox.com', 'mobgold.com', 'mobi24.net', 'mobicont.com', 'mobidevdom.com',
        'mobifobi.com', 'mobile-10.com', 'mobile-app-vault.life', 'mobile-protoshield.eu', 'mobile-sys-tem.com',
        'mobileapi.mobiquitynetworks.com', 'mobileapptracking.com', 'mobilerevenu.com', 'mobiright.com', 'mobisla.com',
        'mobizme.net', 'moborobot.com', 'mobsterbird.info', 'mobstrks.com', 'mobtop.ru', 'mobtrks.com', 'mobtyb.com',
        'mobylog.jp', 'mobytrks.com', 'mocean.mobi', 'mokuz.ru', 'moneroocean.stream', 'moneycdn.com',
        'moneycosmos.com', 'moneymakercdn.com', 'moneywhisper.com', 'monkeybroker.net', 'monkeyminer.net',
        'moonicorn.network', 'mopub.com', 'moregamers.com', 'morgdm.ru', 'moviesprofit.com', 'mpltrack.com',
        'mpmcash.com', 'mpuls.ru', 'mrskincash.com', 'ms3388.com', 'msg.ettoday.net', 'msgose.com', 'mspredom.com',
        'mstat.ga', 'mt.sellingrealestatemalta.com', 'mto.mediatakeout.com', 'mtrack.nl', 'mtracking.com',
        'mugammaconsultants.com', 'mwgol.com', 'mxcdn.net', 'myadcash.com', 'mycdn.co', 'mycdn2.co', 'mydas.mobi',
        'myfavcelebs.com', 'myfinance.com', 'myjaina.com', 'myscoop-tracking.googlecode.com', 'mysocialpixel.com',
        'mytrackf73.com', 'myvisitors.se', 'naiadexports.com', 'naleapprength.xyz', 'nanda.vn', 'nastydollars.com',
        'nativeadmatch.com', 'nativepu.sh', 'nativeroll.tv', 'naughtybuddyswoop.com', 'nawpush.com', 'nbstatic.com',
        'ncaudienceexchange.com', 'ndroip.com', 'negyuk.com', 'neltoole.net', 'netshelter.net', 'new-sports-bonus.com',
        'newideasdaily.com', 'newnudecash.com', 'newrelic.com', 'newrelisc.com', 'newscribes.com', 'newsmaxwidget.com',
        'newspaperlove.com', 'newsubscribes.com', 'nextbdom.ru', 'nextoptim.com', 'nextyourcontent.com',
        'ngastatic.com', 'nikkiscash.com', 'nimiq.watch', 'ningme.ru', 'niuosnd.ru', 'nmcdn.us', 'nmentshad.info',
        'noclef.com', 'nol.yahoo.com', 'nompakru.click', 'nonpaly.ru', 'nonpareilwagetide.com', 'notifyvisitors.com',
        'novelty.media', 'nr-data.net', 'nscash.com', 'nsg.symantec.com', 'ntv.io', 'ntvk1.ru', 'ntvpevents.com',
        'ntvpwpush.com', 'nuggad.net', 'nui.media', 'numb.hotshare.biz', 'nutaku.net', 'o333o.com', 'oawhaursaith.com',
        'octopuspop.com', 'offerimage.com', 'offoonguser.com', 'ofhappinyer.com', 'ogluyourrvv.com', 'ohchat.net',
        'oimg.m.cnbc.com', 'oimg.mobile.cnbc.com', 'ojrq.net', 'okeo.ru', 'omareeper.com', 'omchanseyr.com',
        'omnitagjs.com', 'onad.eu', 'ondu.ru', 'onepush.app', 'onepush.query.yahoo.com', 'onestat.com',
        'onetag-sys.com', 'onetouch6.com', 'onetouch8.info', 'onhercam.com', 'onlinepbx.ru', 'onmarshtompor.com',
        'onpato.ru', 'onscroll.com', 'onstunkyr.com', 'onthe.io', 'oops.redditmedia.com', 'openmediation.com',
        'openx.net', 'opsoomet.net', 'opstag.com', 'optimizesrv.com', 'optimost.com', 'optmnstr.com',
        'oughtbuilding.com', 'ousseventi.info', 'outbalancecapitalist.com', 'outchinchour.com', 'overture.com',
        'ox-i.cordillera.tv', 'p.adbrn.com', 'pagefair.com', 'pagerankfree.com', 'paginw.com', 'paidsearchexperts.com',
        'paishuno.net', 'palasidedoor.com', 'paradocs.ru', 'pardina.ru', 'pardot.com', 'parrable.com', 'parsely.com',
        'particlesmanuscript.com', 'partymidge.com', 'passiveinitialclass.com', 'passivemarcoanyhow.com',
        'patchovercome.com', 'patiskcontentdelivery.info', 'payingnoodlescam.com', 'pbstck.com',
        'pclick.europe.yahoo.com', 'pclick.internal.yahoo.com', 'pclick.yahoo.com', 'peachtrackerus.com', 'pecash.com',
        'peekme.cc', 'peer39.com', 'penjazzvice.com', 'peppy2lon1g1stalk.com', 'perfectmarket.com',
        'perfunctorytalentcompute.com', 'permutive.com', 'perr.h-cdn.com', 'pglstatp.com', 'pgmediaserve.com',
        'pharmcash.com', 'pheegoab.click', 'phengung.net', 'phoenix-widget.com', 'phoobsoo.net', 'pictureturn.com',
        'pignuwoa.com', 'piguiqproxy.com', 'ping-fast.com', 'pip-pip-pop.com', 'pisism.com', 'pix.nbcuni.com',
        'pix.speedbit.com', 'pix.telekom.de', 'pixel-a.basis.net', 'pixel.ad', 'pixel.facebook.com', 'pixeleze.com',
        'pixelpop.co', 'pixelrevenue.com', 'pixels.boxberry.ru', 'pixels.livingsocial.com', 'pixelsfighting.co',
        'pixiv.org', 'pixxur.com', 'pkeeper3.ru', 'placed.com', 'placemypixel.com', 'pladform.ru',
        'platform.communicatorcorp.com', 'platform.iteratehq.com', 'platformpanda.com', 'player.streamshow.it',
        'playstream.media', 'playuhd.host', 'plugin.me2day.net', 'plugin.ws', 'plumbus.minutemediaservices.com',
        'plusone.google.com', 'pmbox.biz', 'pmpubs.com', 'points2shop.com', 'polishshinyspectacles.com',
        'politicianbusplate.com', 'polyad.net', 'poogriry.click', 'poonproscash.com', 'pop-rev.com', 'pop.fapxl.com',
        'popander.com', 'popcash.net', 'popclck.net', 'popcpm.com', 'popearn.com', 'popin.cc', 'popmajor.com',
        'popmarker.com', 'popmog.com', 'popnc.com', 'poppcheck.de', 'popped.biz', 'poppysol.com', 'pops.freeze.com',
        'popsample.com', 'popt.in', 'popularitish.com', 'populis.com', 'populisengage.com', 'populr.me', 'popwin.net',
        'popxxx.net', 'pornedup.com', 'porno-file.ru', 'pos.baidu.com', 'possepairsad.com', 'post.rmbn.ru',
        'postlnk.com', 'potwm.com', 'pouluwie.net', 'powerad.ai', 'powerapp.download', 'powercount.com',
        'pr-static.empflix.com', 'pr.comet.yahoo.com', 'predictad.com', 'premium.naturalnews.tv', 'premium4kflix.top',
        'preparedtennismissionary.com', 'presage.io', 'presentlyarch.com', 'primechoice.ru', 'primis.tech',
        'private.camz.', 'privdef-track.com', 'privy.com', 'prmtracking.com', 'proffigurufast.com',
        'profile.bharatmatrimony.com', 'profilesnitch.com', 'profitabledisplaycontent.com', 'projectadv.it',
        'projectagoraservices.com', 'projectsunblock.com', 'promoted.soundcloud.com', 'promotools.biz', 'propu.sh',
        'prosperitypartying.com', 'prosumsit.com', 'protection-privex.com', 'protizer.ru', 'proveexclusionaye.com',
        'provesrc.com', 'providentsopport.site', 'proxypage.msn.com', 'prpopss.com', 'prre.ru', 'prscripts.com',
        'psoapeez.click', 'ptcdn.mbicash.nl', 'ptoahaistais.com', 'ptoushoa.com', 'ptsc.shoplocal.com', 'ptwebcams.com',
        'publicgood.com', 'publicidad.net', 'publisherlabpodcast.com', 'publy.net', 'pubmatic.com', 'pubmine.com',
        'pubnative.net', 'pulpix.com', 'pulpsbarndomed.com', 'pulsar.ebay.com', 'purevideo.com', 'pusbaysgreedy.icu',
        'push-free.com', 'pusharest.com', 'pushengage.com', 'pushic.com', 'pushiki.ru', 'pushkintop.ru',
        'pushportable.xyz', 'pushprofit.ru', 'pushub.net', 'pushvip.ru', 'pushworldtool.com', 'pussyeatingclubcams.com',
        'pvtag.yahoo.co.jp', 'px-cloud.net', 'px.excitedigitalmedia.com', 'px.staticfiles.at', 'qlogo.cn',
        'quadrupleclick.com', 'quant.jp', 'quantcount.com', 'quantserve.com', 'quicksilver.scdn.co',
        'qwertyamerica.com', 'qwertytracks.com', 'r.msn.com', 'r.my.com', 'raboninco.com', 'racesstuffing.com',
        'railroadtomato.com', 'rangparenting.com', 'rapgasyogin.com', 'rapidtrk.net', 'rapidyl.net', 'rareru.ru',
        'ratemyshaft.com', 'rating-widget.com', 'rayjump.com', 'rdtk.io', 'readrboard.com', 'real5traf.ru',
        'realitycash.com', 'reallifecam.com', 'realmatch.com', 'realpush.media', 'realsrv.com', 'realtime-bid.com',
        'rearrangeapostrophemargarita.com', 'reasonalattracke.info', 'reasonexpe.info',
        'recentrecentinsectsquantity.com', 'recyclesubsidedplight.com', 'redfastlabs.com', 'redzxxxtube.com',
        'registrybrotherinlawdots.com', 'regulationprivilegescan.top', 'rekodpro.com', 'rekovers.ru', 'rel.msn.com',
        'relevantairbornefantastic.com', 'rem-track.bild.de', 'remarketingpixel.com', 'remising.xyz', 'renceriskie.fun',
        'rently-neutions.com', 'reojou.com', 'repelis.id', 'repixel.co', 'requiredcollectfilm.info', 'rereddit.com',
        'resolutioncomplexionfinishing.com', 'retargeting.biz', 'retrack.q-divisioncdn.de', 'revcontent.com',
        'revimedia.com', 'revmob.com', 'revrtb.net', 'rexbucks.com', 'rfihub.com', 'rfksrv.com', 'rhythmxchange.com',
        'rich-agent.s3.amazonaws.com', 'richaudience.com', 'ridferbad.com', 'riflereddenproved.com', 'rilelogicbuy.com',
        'rincegath.fun', 'rinedcountilconsiden.info', 'rivcash.com', 'riverhit.com', 'riverpush.com', 'rkdms.com',
        'rlcdn.com', 'rnmd.com', 'rockincontent.net', 'roia.biz', 'roia.hutchmedia.com', 'rotaban.ru', 'roujaufu.net',
        'roujonoa.net', 'royal-cash.com', 'rsdescriptsrem.info', 'rseyebrown.fun', 'rtbpop.com',
        'rubcomplaintdimly.com', 'rubiconproject.com', 'rum.azioncdn.net', 'rummaring.pics', 'run-syndicate.com',
        'runghollow.com', 'runnersgunpowder.com', 'rusenov.com', 'russianlovematch.com', 'rutarget.ru', 's-onetag.com',
        's7target.ru', 'sa.api.intl.miui.com', 'sabin.free.fr', 'safedk.com', 'safellk.com', 'sail-horizon.com',
        'sail-personalize.com', 'salefile.googlecode.com', 'samsungusa.com', 'sana.newsinc.com.s3.amazonaws.com',
        'sape.ru', 'saturdayloathe.com', 'saymedia.com', 'sb4you1.com', 'sc-static.net', 'sc.othman.tv',
        'scarabresearch.com', 'sceno.ru', 'schjmp.com', 'scnt.rambler.ru', 'scontent.services.tvn.pl',
        'scorecardresearch.com', 'scout.haymarketmedia.com', 'screencapturewidget.aebn.net', 'screenpopper.com',
        'scribe.twitter.com', 'script.ag', 'scriptil.com', 'scripts.mailfire.io', 'scripts21.com', 'scrubswim.com',
        'scupio.com', 'search.twitter.com', 'secretbehindporn.com', 'secretrune.com', 'secretturtle.com',
        'secureaddisplay.com', 'securesurf.biz', 'security-protect.systems', 'security-update-required.com',
        'seemybucks.com', 'seg.sharethis.com', 'sekindo.com', 'selectserialcage.com', 'sem.triboomedia.it',
        'sendsay.ru', 'seninezor.xyz', 'sense360eng.com', 'serating.ru', 'seriousfiles.com', 'services.hmhost.co.uk',
        'serving-sys.com', 'sessioncam.com', 'sessions.exchange', 'setpadchat.com', 'setupad.com', 'sexad.net',
        'sexdatecash.com', 'sexmoney.com', 'sexplaycam.com', 'sgsnssdk.com', 'share.baidu.com', 'share.itraffic.su',
        'share.pluso.ru', 'share.static.skyrock.net', 'share.yandex.ru', 'shareaholic.com', 'sharecash.org',
        'sharedcount.com', 'sharedheels.com', 'shareitpp.com', 'sharethis.com', 'sharethrough.com',
        'shesubscriptions.com', 'shitcustody.com', 'shoofle.tv', 'shopalyst.com', 'shopeasy.by', 'shopilize.com',
        'shopnetic.com', 'shoppanda.co', 'shopping-moda.it', 'shopzyapp.com', 'shostobs.net', 'showcasead.com',
        'showcasethat.com', 'siccash.com', 'sift.co', 'sillrochester.com', 'silvergamed.com', 'silverpop.com',
        'simplereach.com', 'simplewebanalysis.com', 'sinaimg.cn', 'singular.net', 'sinisterdinepuberty.com',
        'sioncenture.fun', 'site.flashx.', 'sitemaji.com', 'sitemeter.com', 'sitescout.com', 'sitestat.com',
        'siteswithcontent.com', 'sjv.io', 'skpharmacy.in', 'skytvonline.tv', 'slipstream.skyscanner.net', 'smaato.net',
        'smartadv.ru', 'smartasset.com', 'smartbn.ru', 'smblock.s3.amazonaws.com', 'smcheck.org', 'smi2.ru',
        'smilered.com', 'smilewanted.com', 'smileycentral.com', 'smiling.video', 'smpop.icfcdn.com', 'smrt.as',
        'snapdeal.biz', 'snapwidget.com', 'sndkorea.nowcdn.co.kr', 'snitswaspshaft.com', 'social-sb.com', 'social9.com',
        'socialannex.com', 'socialbirth.com', 'socialelective.com', 'socialhoney.co', 'sociallist.org',
        'sociallypublish.com', 'socialmarker.com', 'socialmedia.com', 'socialmediabuttons.com', 'socialoomph.com',
        'socialprofitmachine.com', 'socialproof.it', 'socialreach.com', 'socialrest.com', 'socialsex.biz',
        'socialsex.com', 'socialsexnetwork.net', 'socialspark.com', 'socialtwist.com', 'socialvibe.com',
        'solutionzip.info', 'somersetcountygazette.co.uk', 'sonobi.com', 'spillsackterrified.com',
        'spinbox.freedom.com', 'splicky.com', 'splittingpick.com', 'sportsyndicator.com', 'sporttv.today',
        'spotim.market', 'spotx.tv', 'spotxchange.com', 'sprinklecontent.com', 'spunkycash.com',
        'squeezedthoughtfully.com', 'srtb.msn.com', 'ssacdn.com', 'ssaimg.com', 'ssionsupre.fun', 'sskmnews.pro',
        'st.cdnco.us', 'stack-sonar.com', 'stagepopkek.com', 'staging.tree', 'staqdata.com', 'startappexchange.com',
        'startappservice.com', 'staticiv.com', 'staticsfs.host', 'statictapcdn-a.akamaihd.net', 'staticxz.com',
        'statowl.com', 'stats.wp.com', 'stawhoph.com', 'steadfastsound.com', 'steadfastsystem.com', 'steepto.com',
        'stooptobacco.com', 'stoutoffering.com', 'strangersincentive.com', 'strayhepatitisbruise.com', 'streamx.me',
        'streamyourvid.com', 'strikeadcdn.s3.amazonaws.com', 'studentloan.host', 'styleui.ru', 'submitexpress.co.uk',
        'subpixel.4players.de', 'successcompassion.com', 'suibyuming.com', 'summerhamster.com', 'sumrep.com', 'sun.win',
        'suntcontent.se', 'superbuzz.io', 'supertrackingz.com', 'superwidget-assets.gowatchit.com', 'surfingbird.ru',
        'survey.io', 'surveywall-api.survata.com', 'survicate.com', 'sv2.biz', 'sweepawejasper.com', 'swiftmining.win',
        'swiftypecdn.com', 'symkashop.ru', 'sync.tv', 'syndicate.payloadz.com', 'syndicatedsearchresults.com',
        'syndication.jsadapi.com', 'synovite-scripts.com', 'syxylyche.pro', 't.a3cloud.net', 't.adlpo.com',
        't.brand-server.com', 'tabookbusines.info', 'tag.1rx.io', 'tag.aticdn.net', 'tagbucket.cc', 'tagcdn.com',
        'tags.cdn.circlesix.co', 'tags.msnbc.com', 'tailtarget.com', 'talkasia.info', 'tapfiliate.com', 'tapjoy.com',
        'targaubs.com', 'tbe.tom.ru', 'tbex.ru', 'tce.alicdn.com', 'tcimg.com', 'tdf1.admyjob.com', 'teachcoexist.com',
        'teasernet.ru', 'tech-board.com', 'telemetry.soundcloud.com', 'telvanil.ru', 'temposnitehah.work', 'tenmax.io',
        'teralog.techhub.co.kr', 'terethat.ru', 'terraclicks.com', 'tgpsew.com', 'thaickoo.net',
        'the-adult-company.com', 'the-binary-trader.biz', 'thelovebucks.com', 'themoneytizer.com', 'thepcspy.com',
        'therapistpopulationcommentary.com', 'therebelfasters.info', 'thesocialsexnetwork.com',
        'thetradedesk-tags.s3.amazonaws.com', 'third-tracking.com', 'thisisdax.com', 'thisisthewestcountry.co.uk',
        'thismetric.com', 'thrustdeadconsiderably.com', 'tkcatrun.aotter.net', 'tnative.ru', 'toeschistache.com',
        'toget.ru', 'toglooman.com', 'tollfreeforwarding.com', 'tools.gfcash.com', 'top100-images.rambler.ru',
        'top100.rambler.ru', 'top100.ru', 'top100webshops.com', 'topad.mobi', 'topbingowebsites.co.uk',
        'topclickguru.com', 'topeuro.biz', 'tr.cloud-media.fr', 'trace.events', 'tracelog.www.alibaba.com',
        'track-app.club', 'track-patapp.com', 'track-safe.com', 'track2.me', 'trackad2.com', 'tracker-tds.info',
        'tracker.twenga.', 'trackerislive.com', 'tracking202.com', 'trackingzen.com', 'trackinz.com',
        'trackmkxoffers.se', 'trackonomics.net', 'trackpush.com', 'trackspeeder.com', 'tracktraf.com', 'trackuity.com',
        'trackvoluum.com', 'tradeexpert.net', 'tradescape.biz', 'traffbiz.ru', 'traffic-media.co',
        'traffic.acwebconnecting.com', 'traffic.buyservices.com', 'traffic.ru', 'traffic.tc-clicks.com', 'traffic4u.nl',
        'trafficbroker.com', 'trafficdelivery1.com', 'trafficfactory.biz', 'trafficforce.com',
        'trafficfuelpixel.s3-us-west-2.amazonaws.com', 'trafficguard.ai', 'traffichaus.com', 'trafficholder.com',
        'trafficrouter.io', 'trafficshop.com', 'trafficstars.com', 'traffictrader.net', 'traffictraffickers.com',
        'trafforsrv.com', 'trafiq.party', 'trailers.cn77nd.com', 'trakksocial.googlecode.com', 'traktrafficflow.com',
        'tree-pixel-log.s3.amazonaws.com', 'tree.com', 'trellian.com', 'tremblingkeyboardassistant.com',
        'tribalfusion.com', 'trk.adbutter.net', 'trk.pinterest.com', 'trkn.us', 'trmnsite.com', 'trombocrack.com',
        'true2file.com', 'truefilen32.com', 'truelimitinvestment.com', 'trunblock.com', 'trunkmafia.com', 'trustx.org',
        'tsyndicate.com', 'ttauri.creativebloq.com', 'ttdetect.staticimgfarm.com', 'tubeadv.com', 'tubechat.eu',
        'tubecorporate.com', 'tubedspots.com', 'tubemogul.com', 'tubepush.eu', 'tubereplay.com', 'turn.com',
        'tutotrack.com', 'tvpixel.com', 'tweetboard.com', 'twinesocial.com', 'twinrdsrv.com', 'twinred.com',
        'twistyscash.com', 'twitter-badges.s3.amazonaws.com', 'twittericon.com', 'tynt.com', 'ucfeed.ru',
        'udc.yahoo.com', 'udcm.yahoo.com', 'uestat.video.qiyi.com', 'ufpcdn.com', 'ulukaris.com',
        'unacceptableclevercapable.com', 'unagi-na.amazon.com', 'unblocksource.com', 'underdividedhowever.com',
        'underdog.media', 'undertone.com', 'underwearnavigable.com', 'unionapps.info', 'unlockr.com', 'unrulymedia.com',
        'unwofulcountys.com', 'upgulpinon.com', 'uptpro.homestead.com', 'uralweb.ru', 'urbanpieup.com', 'uriren.pw',
        'urlcash.net', 'urtirepor.com', 'us-fortressprotection.com', 'usabilla.com', 'usage.seibert-media.io',
        'usenetnl.download', 'user-shield.com', 'usercash.com', 'ushoofop.com', 'utarget.ru', 'utrack.hexun.com',
        'utubeconverter.com', 'uwonderful.ru', 'v.emedia.cn', 'valuad.cloud', 'valuewalk.com', 'vaneplusnod.com',
        'vapourgrievously.com', 'vashoaft.net', 'vdtrack.com', 'venatusmedia.com', 'venturead.com', 'verizonmedia.com',
        'versatileadvancement.com', 'veve.com', 'viaplays.com', 'viatepigan.com', 'vice-publishers-cdn.vice.com',
        'vicegnem.click', 'vidazoo.com', 'vidbem.com', 'video-adblocker.com', 'video-api.yql.yahoo.com',
        'video-loader.com', 'video-people.com', 'video.oms.eu', 'videoadex.com', 'videodeals.com', 'videoegg.com',
        'videohub.com', 'videoindigen.com', 'videoplayerhub.com', 'videoroll.net', 'videos.oms.eu', 'vidigital.ru',
        'vihub.ru', 'vipicmou.net', 'vira.ru', 'visit.asb.co.nz', 'visit.dealspwn.com', 'visit.mobot.net',
        'visit.webhosting.yahoo.com', 'visitorglobe.com', 'visitorinspector.com', 'visitorjs.com', 'visitorpath.com',
        'visitorprofiler.com', 'visitors.sourcingmap.com', 'visitorville.com', 'visitping.rossel.be', 'visits.lt',
        'visitstreamer.com', 'visitweb.com', 'visualwebsiteoptimizer.com', 'vividcash.com', 'vividlobster.com',
        'vlitag.com', 'vntsm.com', 'voapozol.com', 'vod-cash.com', 'vogo-vogo.ru', 'vogorana.ru', 'vogozae.ru',
        'voluumtracker.com', 'votes.buzz.yahoo.com', 'vpadn.com', 'vpnfortorrents.cc', 'vpnmightberequired.xyz',
        'vserv.bc.cdn.bitgravity.com', 'vserv.mobi', 'vsexshop.ru', 'vtracker.net', 'vulturechinamaternity.com',
        'vungle.com', 'w.homes.yahoo.net', 'waframedia5.com', 'wamcash.com', 'wapdollar.in', 'warswhitawe.com',
        'watchfree.flv.in', 'waycash.net', 'wayfarerspoutpraise.com', 'webassembly.stream', 'webcambait.com',
        'webcampromo.com', 'webcampromotions.com', 'webcams.com', 'webcontentassessor.com', 'webcontentdelivery.info',
        'webiqonline.com', 'webpinp.com', 'webplus.info', 'webpu.sh', 'webpushr.com', 'webstat.cc', 'webstats.sapo.pt',
        'webtalking.ru', 'webteaser.ru', 'webtrack.biz', 'webtracker.jp', 'webtraffic.se', 'webtraffic.ttinet.com',
        'webtrends.com', 'webtrendslive.com', 'webturn.ru', 'webvisor.org', 'wedgeenclosed.com', 'wetpeachcash.com',
        'whippedfreezerbegun.com', 'whiteboardnez.com', 'whitepixel.com', 'whitepush.biz', 'whoevercloakroom.com',
        'whoisvisiting.com', 'wholesomeindians.com', 'whugesto.net', 'widget.clipix.com', 'widget.clym-sdk.net',
        'widget.crowdignite.com', 'widget.jobberman.com', 'widget.pico.tools', 'widget.quantcast.com',
        'widget.stagram.com', 'widget.weibo.com', 'widget.whatshelp.io', 'widget.yavli.com', 'widget.zoorate.com',
        'widgetbucks.com', 'widgetly.com', 'widgets.comcontent.net', 'widgets.dzone.com', 'widgets.fie-data.co.uk',
        'widgets.getpocket.com', 'widgets.itaringa.net', 'widgets.junction.co.za', 'widgets.lendingtree.com',
        'widgets.mobilelocalnews.com', 'widgets.mozo.com.au', 'widgets.pinterest.com', 'widgets.realestate.com.au',
        'widgets.seekitlocal.com', 'widgets.solaramerica.org', 'widgets.stripst.com', 'widgets.tapcdn.com',
        'widgets.tree.com', 'widgets.trustedshops.com', 'widgetsplus.com', 'widgetssec.cam-content.com',
        'wifecrytrade7.live', 'wifelovers.com', 'wigetmedia.com', 'wildmatch.com', 'wisepops.com', 'wistia.com',
        'wizhumpgyros.com', 'wmgtr.com', 'wojdn.com', 'womanear.com', 'womenblazingtrails.com', 'worldsbestcams.com',
        'wowreality.info', 'wpu.sh', 'wpush.biz', 'wt.adtrue24.com', 'wwgate.ru', 'wysistat.com',
        'x.fidelity-media.com', 'xay5o.toscane-boutique.fr', 'xclicks.net', 'xe9o.xyz', 'xfast.host',
        'xhamstercams.com', 'xing-share.com', 'xiti.com', 'xlovecam.com', 'xplosion.de', 'xtendmedia.com',
        'xtrack.capetown.gov.za', 'xuossk3tu6hb.com', 'xxlargepop.com', 'xxxmatch.com', 'xzipy.com', 'y8z.org',
        'yadro.ru', 'yahoo.media.net', 'yappaapp.com', 'yazcash.com', 'yeaonesad.com', 'yeas.yahoo.co.jp',
        'yellowblue.io', 'yext-pixel.com', 'yiatelychur.top', 'yjtag.yahoo.co.jp', 'yldbt.com', 'yldmgrimg.net',
        'yoc.mobi', 'yottacash.com', 'you-have-won-h1jk.live', 'youearrid.com', 'younetmedia.com', 'your-notice.com',
        'yourlocalguardian.co.uk', 'yourmedieve.com', 'yourwebbars.com', 'youtube.local', 'yupfiles.net',
        'yurivideo.com', 'zaehler.tv', 'zangocash.com', 'zap.buzz', 'zbet.com', 'zcoup.com', 'zedo.com',
        'zenhppyad.com', 'zenoviaexchange.com', 'zeotap.com', 'zergnet.com', 'zerolullaby.com', 'ziphentai.com',
        'zipropyl.com', 'zoaheeth.com', 'zopim.com', 'zouphail.com', 'zqtk.net', 'zumcontentdelivery.info',
        'zuphaims.com'
    ];
    const blockedShUrlRegexes = [
        '*.adcolony.com*', '*/banner/*', '*1e3af*', '*2sa8l*', '*2sh8k*', '*3hof2*', '*3r1kw*', '*3wnp9', '*493b9*',
        '*5kdnf*', '*777*partner*', '*8s32e*', '*9dje1*', '*9epe1*', '*9ov3l*', '*9qovc*', '*9za10*', '*a1253*',
        '*a9dly*', '*ad*xiaomi*', '*ad-spec*', '*adasset*', '*adbit*', '*adblock*', '*adboost*', '*adcell*',
        '*adchoices*', '*adclick*', '*adcouncil*', '*addthis*', '*adebis*', '*adevent*', '*adexchange*', '*adexp*',
        '*adezr*', '*adfarm*', '*adfeedback*', '*adglare*', '*adhese*', '*adimag*', '*adimg*', '*aditms*',
        '*adjuggler*', '*adlip*', '*adlog*', '*admarket*', '*admaster*', '*admob*', '*adnet*', '*adnsv*', '*adoverlay*',
        '*adqva*', '*adqy6*', '*adroll*', '*ads*', '*adtago*', '*adtaily*', '*adtech*', '*adtrx*', '*advert*',
        '*adviceiq*', '*advinci*', '*adx*', '*affiliat*', '*ahaumplab*', '*alexametrics*', '*alxbg*', '*analytics*',
        '*anamuel-careslie*', '*apecrilaconz*', '*apl*.me*', '*appflood*', '*appier*', '*appmetric*', '*arunz*',
        '*atdmt*', '*atlant-track*', '*autopromo*', '*aybob*', '*b86d4*', '*banner*', '*beonixom*', '*bestcond*tions*',
        '*bggzn*', '*bidswitch*', '*bngpt*', '*bonertraffic*', '*brucelead*', '*bugsnag*', '*campaign*id*',
        '*camplacecash*', '*cashtrafic*', '*chartbeat*', '*chartboost*', '*chitlurkedoaks*', '*click.oneplus*',
        '*clicksor*', '*clicktale*', '*cmtmz*', '*coinad*', '*conversant*', '*corover*', '*cpcalendars*',
        '*cpcontacts*', '*crashlytics*', '*criteo*', '*crittercism*', '*czx5e*', '*d11x7*', '*d1b0f*', '*d1e28*',
        '*d1f05*', '*d1f0e*', '*d1fs2*', '*d1lu3*', '*d1oto*', '*d1r90*', '*d1ukp*', '*d1vl8*', '*d1ybd*', '*d1z2j*',
        '*d22sf*', '*d27gt*', '*d2kad*', '*d2lmf*', '*d2p3z*', '*d2sbz*', '*d2uap*', '*d2uy8*', '*d2v02*', '*d2wy8*',
        '*d303e*', '*d31qb*', '*d330a*', '*d35u1*', '*d36zf*', '*d3al5*', '*d3dyt*', '*d3hb1*', '*d3ith*', '*d3m4h*',
        '*d3mr7*', '*d3mzo*', '*d3t3z*', '*d3u59*', '*d3v3b*', '*dc5k8*', '*dealtime*', '*dje10*', '*djtfl*', '*dmmzk*',
        '*dnhfi*', '*dnn50*', '*doubleclick*', '*doubleverify*', '*dq3yx*', '*dqnp8*', '*dr5dy*', '*dtv5l*', '*dtyry*',
        '*dvqig*', '*dw7nr*', '*dwzg4*', '*e6989*', '*emediate*', '*emxdgt*', '*esomniture*', '*etracke*', '*eventlog*',
        '*exoclick*', '*exosrv*', '*ezoic*', '*f9d1p*', '*fastclick*', '*fcmatch*', '*fcukfriend*', '*fe9xg*',
        '*filament*', '*fingerarts*', '*freegeoip*', '*fstsrv*', '*fusepowered*', '*fwmrm*', '*getad*', '*gffts*',
        '*goaffmy*', '*gosquared*', '*gotrackier*', '*gslyy*', '*gxwjk*', '*histats*', '*hotjar*', '*hpyrdr*',
        '*http://ad.*', '*http://ads.*', '*http://ad0.*', '*http://ad1.*', '*http://ad2.*', '*http://ad3.*',
        '*http://ad4.*', '*http://ad5.*', '*http://ad6.*', '*http://ad7.*', '*http://ad8.*', '*http://ad9.*', '*hsh51*',
        '*icemochi*', '*imglnk*', '*impression*', '*indieclick*', '*interad*', '*interst*', '*ironsrc*', '*iryaz*',
        '*isfxs*', '*ismta*', '*jairoowe*', '*kshzz*', '*lencr*', '*liftoff*', '*lijit*', '*littlecdn*', '*logbak*',
        '*logservice*', '*lolopod*', '*lsefd*', '*luckyorange*', '*lya10*', '*markete*', '*marketi*', '*marketo*',
        '*medialytics*', '*metartmoney*', '*metrics*.data*', '*metrics-dra*', '*microad*', '*mistat*', '*moatpixel*',
        '*mobile-creatives*', '*mobile_tracking*', '*mobilefuse*', '*mol11*', '*mopinion*', '*mouseflow*',
        '*mparticle*', '*mpulse*', '*mr2cn*', '*mrjb7*', '*myadx*', '*nbf9b*', '*nddmc*', '*nedstat*',
        '*newsandpromotions*', '*nhagz*', '*noopener*', '*nsstatic*', '*onclick*', '*open.oneplus*', '*optad360*',
        '*outbrain*', '*p2r14*', '*p3331*', '*pagead*', '*partnerad*', '*pixfuture*', '*placeholder*', '*placement*',
        '*pop-vndata*', '*popmonetizer*', '*popunder*', '*popup*', '*preroll*', '*promo-*', '*promo.*', '*propeller*',
        '*protomob*', '*publicidade*', '*pushails*', '*qfjhe*', '*rqyou*', '*rsalt*', '*rskno*', '*rtmark*',
        '*rtpdn11*', '*runative*', '*s3t3d*', '*secretmedia*', '*securemetrics*', '*securepubads*', '*sentry*',
        '*sflyy*', '*shinystat*', '*shostsobs*', '*slickmodal*', '*smartad*', '*smarturl*', '*smetrics*', '*snfzm*',
        '*socialbars*', '*special-offers*', '*speee-ad*', '*sponsor*', '*staticstuff*', '*streamrail*', '*stroeer*',
        '*supportmetrics*', '*swrve*', '*synthasite*', '*taboola*', '*tagtoo*', '*textad*', '*thousoucm*', '*toc8o*',
        '*tracking*miui*', '*trafficjunky*', '*tremormedia*', '*truepush*', '*u002D*', '*u2xee*', '*u9sj1*',
        '*udookrou*', '*umcja*', '*umeng*', '*usyak*', '*valueclick*', '*vegacdn*', '*vermarktung*', '*voodoo*',
        '*vpn*plus*', '*whistleout*', '*wkctj*', '*xgwsl*', '*ybotv*', '*ye185h*', '*yield*', '*yjvim*', '*ypjoc*',
        '*ythome*', '*yumenetworks*', '*zbdvv*', '*zenclerk*', '*zffum*', '*zyadw*'
    ];
    
    if(testMatchesHostsOrShUrlRegexes(url, host, allowedHosts, allowedShUrlRegexes)) {
        return ALLOW;
    }
    else if(testMatchesHostsOrShUrlRegexes(url, host, bypassUrlHosts, bypassShUrlRegexes)) {
        return BYPASS;
    }
    else if(testMatchesHostsOrShUrlRegexes(url, host, blockedHosts, blockedShUrlRegexes)) {
        return MYBLOXX;
    }
    return ALLOW;
}
