//
// Testing PAC
// 
// ┏━┓┏━┳┓╋╋┏┳┓╋┏┓╋╋╋┏━┓┏━┳━┓┏━┓
// ┃┃┗┛┃┃┗┓┏┛┃┃╋┃┃╋╋╋┗┓┗┛┏┻┓┗┛┏┛
// ┃┏┓┏┓┣┓┗┛┏┫┗━┫┃┏━━┓┗┓┏┛╋┗┓┏┛
// ┃┃┃┃┃┃┗┓┏┛┃┏┓┃┃┃┏┓┃┏┛┗┓╋┏┛┗┓
// ┃┃┃┃┃┃╋┃┃╋┃┗┛┃┗┫┗┛┣┛┏┓┗┳┛┏┓┗┓
// ┗┛┗┛┗┛╋┗┛╋┗━━┻━┻━━┻━┛┗━┻━┛┗━┛
// 
// Powered by MYXX FM
// #1 for Spanglish Hits!
// MYXXfm.com | MYXX-DB | Dallas, TX
//
var PROXY_DIRECT = "DIRECT";
var DIRECT = "DIRECT";
function s(u, r) {
	return shExpMatch(u, r);
} 
function FindProxyForURL(url, host) {
	var u = url.toLowerCase();
	
	if (s(u, "*aclk*") ||
s(u, "*acloudimages*") ||
s(u, "*acloudvideos*") ||
s(u, "*adap.tv*") ||
s(u, "ad*.*.*") ||
s(u, "ad*-*.*") ||
s(u, "*adasset*") ||
s(u, "*adchoices*") ||
s(u, "*adcolony*") ||
s(u, "*adcouncil*") ||
s(u, "*adexchange*") ||
s(u, "*adexprt*") ||
s(u, "*adfarm*") ||
s(u, "*adfeedback*") ||
s(u, "*adimag*") ||
s(u, "*adimg*") ||
s(u, "*aditms*") ||
s(u, "*adk2*") ||
s(u, "*adlog*") ||
s(u, "*adlooxtracking*") ||
s(u, "*admob*") ||
s(u, "*adnet*") ||
s(u, "*adpushup*") ||
s(u, "*adroll*") ||
s(u, "*adsapi*") ||
s(u, "*adsatt*") ||
s(u, "*adsbygoogle*") ||
s(u, "*adscience*.*") ||
s(u, "*adsense*") ||
s(u, "*adserv*") ||
s(u, "*adskeeper*") ||
s(u, "*adsmogo*") ||
s(u, "*adsperk*") ||
s(u, "*adsrv*") ||
s(u, "*adstreamcanvas*") ||
s(u, "*adswizz*") ||
s(u, "*adtech*") ||
s(u, "*adtng*") ||
s(u, "*adtrack*") ||
s(u, "*adtrx*") ||
s(u, "*advert*") ||
s(u, "*affiliate*") ||
s(u, "*ahaumplab*") ||
s(u, "*aimatch*") ||
s(u, "*airship*") ||
s(u, "*altrooz*") ||
s(u, "*assoc-amazon*") ||
s(u, "*amobee*") ||
s(u, "*analytic*") ||
s(u, "*anamuel-careslie*") ||
s(u, "*andomedia*") ||
s(u, "*app-measurement*") ||
s(u, "*appads*") ||
s(u, "*appcenter.ms*") ||
s(u, "*appflood*") ||
s(u, "*applovin*") ||
s(u, "*apprupt*") ||
s(u, "*appsflyer*") ||
s(u, "*atdmt*") ||
s(u, "*atlant-track*") ||
s(u, "*atwola*") ||
s(u, "*banner*") ||
s(u, "*bbelements*") ||
s(u, "*bcfads*") ||
s(u, "*beonixom*") ||
s(u, "*bestcond*tions*") ||
s(u, "*bestcontent*") ||
s(u, "*betgorebysson*") ||
s(u, "*bidvertis*") ||
s(u, "*bnmla*") ||
s(u, "*brightroll*") ||
s(u, "*brucelead*") ||
s(u, "*btrll*") ||
s(u, "*buysellads*") ||
s(u, "*campaign*") ||
s(u, "*carbonads*") ||
s(u, "*cdnads*") ||
s(u, "*chartboost*") ||
s(u, "*chasteminihaunting*") ||
s(u, "*check-out-this*") ||
s(u, "*chitlurkedoaks*") ||
s(u, "*click.*") ||
s(u, "*clickserv*") ||
s(u, "*clickstat*") ||
s(u, "*clicktr*") ||
s(u, "*clk*") ||
s(u, "*clksite*") ||
s(u, "*cloudmobi*") ||
s(u, "*cogleapad*") ||
s(u, "*collector*") ||
s(u, "*conversant*") ||
s(u, "count*.*.*") ||
s(u, "count*-*.*") ||
s(u, "*cpcalendars*") ||
s(u, "*cpcontacts*") ||
s(u, "*cqcounter*") ||
s(u, "*crashlytics*") ||
s(u, "*creativecdn*") ||
s(u, "*criteo*") ||
s(u, "*crittercism*") ||
s(u, "*crl.apple.com*") ||
s(u, "*dealtime*") ||
s(u, "*deltadna*") ||
s(u, "*doubleclick*") ||
s(u, "*doubleverify*") ||
s(u, "*ds88pc0kw6cvc*") ||
s(u, "*ebaycommercenetwork*") ||
s(u, "*eikegolehem*") ||
s(u, "*emediate*") ||
s(u, "*emetriq*") ||
s(u, "*entrust*") ||
s(u, "*esomniture*") ||
s(u, "*exacttarget*") ||
s(u, "*exoclick*") ||
s(u, "*exosrv*") ||
s(u, "*exponential*") ||
s(u, "*eyewonder*") ||
s(u, "*familinger*") ||
s(u, "*fastclick*") ||
s(u, "*fcukfriend*") ||
s(u, "*fingerarts*") ||
s(u, "*flashtalking*") ||
s(u, "*fluentmobile*") ||
s(u, "*fluffyeaster*") ||
s(u, "*fractionalmedia*") ||
s(u, "*free-coupons*") ||
s(u, "*fstsrv*") ||
s(u, "*fusepowered*") ||
s(u, "*fwmrm*") ||
s(u, "*getad*") ||
s(u, "*globaltraffico*") ||
s(u, "*goaffmy*") ||
s(u, "*google*analytics*") ||
s(u, "*googleads*") ||
s(u, "*googlesyndication*") ||
s(u, "*googletagmanager*") ||
s(u, "*googletagservices*") ||
s(u, "*gotrackier*") ||
s(u, "*govid.co*") ||
s(u, "*graizoah*") ||
s(u, "*grooksom*") ||
s(u, "*hastrk2*") ||
s(u, "*hitbox*") ||
s(u, "*hpyrdr*") ||
s(u, "*hsh51nvkrv*") ||
s(u, "*iadnet*") ||
s(u, "*icemochi*") ||
s(u, "*iclickcdn*") ||
s(u, "*img.ads*") ||
s(u, "*inabsolor*") ||
s(u, "*infolinks*") ||
s(u, "*infopicked*") ||
s(u, "*inmobi*") ||
s(u, "*innovid*") ||
s(u, "*inpagepush*") ||
s(u, "*intellitxt*") ||
s(u, "*interad*") ||
s(u, "*interst12*") ||
s(u, "*interstitial*") ||
s(u, "*iwanttodeliver*") ||
s(u, "*jairoowe*") ||
s(u, "*joyekepus.online*") ||
s(u, "*jumptap*") ||
s(u, "*lalaping*") ||
s(u, "*lijit*") ||
s(u, "*lingeriebarren*") ||
s(u, "*littlecdn*") ||
s(u, "*liverail*") ||
s(u, "logg*.*.*") ||
s(u, "logg*-*.*") ||
s(u, "logs*.*.*") ||
s(u, "logs*-*.*") ||
s(u, "*lolopod*") ||
s(u, "*louchees*") ||
s(u, "*m2pub*") ||
s(u, "*mads*") ||
s(u, "*mainspotvideosfree*") ||
s(u, "*mdotm*") ||
s(u, "*medialets*") ||
s(u, "*medialytics*") ||
s(u, "*menxaio.xyz*") ||
s(u, "metrics*.*.*") ||
s(u, "metrics*-*.*") ||
s(u, "miner*.*.*") ||
s(u, "miner*-*.*") ||
s(u, "*mirando*") ||
s(u, "*moatads*") ||
s(u, "*moatpixel*") ||
s(u, "*mobclix*") ||
s(u, "*mobfox*") ||
s(u, "*mobile-creatives*") ||
s(u, "*mobile_interstitials*") ||
s(u, "*mobileads*") ||
s(u, "*mobileapptracking*") ||
s(u, "*mobilefuse*") ||
s(u, "*mobiletheory*") ||
s(u, "*mocean*") ||
s(u, "*mol11*") ||
s(u, "*mopinion*") ||
s(u, "*mopub*") ||
s(u, "*mparticle*") ||
s(u, "*mr2cnjuh34jb*") ||
s(u, "*mrjb7hvcks*") ||
s(u, "*mxptint.net*") ||
s(u, "*myadx*") ||
s(u, "*mycdn*") ||
s(u, "*mydas*") ||
s(u, "*nbf9b5aurl*") ||
s(u, "*netshelter*") ||
s(u, "*newsandpromotions*") ||
s(u, "*nhagz*") ||
s(u, "*ocsp*") ||
s(u, "*offerimage*") ||
s(u, "*onclick*") ||
s(u, "*onstunkyr*") ||
s(u, "*openvideoads*") ||
s(u, "*openx*") ||
s(u, "*outbrain*") ||
s(u, "*pagead*") ||
s(u, "*parkingcrew*") ||
s(u, "*partner.*") ||
s(u, "*partners.*") ||
s(u, "*pflexads*") ||
s(u, "*pixel.*") ||
s(u, "*placement=*") ||
s(u, "*pm-ads*") ||
s(u, "*popads*") ||
s(u, "*popunder*") ||
s(u, "*popup*") ||
s(u, "*postlnk*") ||
s(u, "*promo.*") ||
s(u, "*propeller*") ||
s(u, "*propu.sh*") ||
s(u, "*protomob*") ||
s(u, "*psma*") ||
s(u, "*pubmatic*") ||
s(u, "*pusbaysgreedy*") ||
s(u, "*pushails*") ||
s(u, "*qfjherc*") ||
s(u, "*quantcount*") ||
s(u, "*rarenok*") ||
s(u, "*rdtk*") ||
s(u, "*readserver*") ||
s(u, "*realsrv*") ||
s(u, "*regulationprivilegescan*") ||
s(u, "*remarketingpixel*") ||
s(u, "*renhadmasandbab*") ||
s(u, "*revmob*") ||
s(u, "*rnmd*") ||
s(u, "*rqtrk*") ||
s(u, "*rsaltsjt*") ||
s(u, "*rtbpop*") ||
s(u, "*rtbsuperhub*") ||
s(u, "*rtmark*") ||
s(u, "*rtpdn11*") ||
s(u, "*rubiconproject*") ||
s(u, "*runative*") ||
s(u, "*rusenov*") ||
s(u, "*scorecardresearch*") ||
s(u, "*security-update-required*") ||
s(u, "*sextracker*") ||
s(u, "*shostsobs*") ||
s(u, "*shyhuetub*") ||
s(u, "*sillrochester*") ||
s(u, "*slickmodal*") ||
s(u, "*smaato*") ||
s(u, "*smartads*") ||
s(u, "*smartclip*") ||
s(u, "*smarturl*") ||
s(u, "*smartyads*") ||
s(u, "*socialbars*") ||
s(u, "*special-offers*") ||
s(u, "*splicky*") ||
s(u, "*sponsored*") ||
s(u, "*spylog*") ||
s(u, "*statcounter*") ||
s(u, "*static-moreinfo*") ||
s(u, "*stats.*") ||
s(u, "*steadfastsystem*") ||
s(u, "*streamstrongcompletelyprogram*") ||
s(u, "*swrve*") ||
s(u, "*synergy*") ||
s(u, "*taboola*") ||
s(u, "*tapjoy*") ||
s(u, "*temposnitehah*") ||
s(u, "*textad*") ||
s(u, "*thousoucm*") ||
s(u, "*.top") ||
s(u, "*tradedoubler*") ||
s(u, "*traffichaus*") ||
s(u, "*trafficjunky*") ||
s(u, "*trafficstars*") ||
s(u, "track*-*.*") ||
s(u, "track*.*.*") ||
s(u, "*transpera*") ||
s(u, "*tribalfusion*") ||
s(u, "*trk.*.*") ||
s(u, "*truepush*") ||
s(u, "*tsyndicate*") ||
s(u, "*u002D*") ||
s(u, "*udookrou*") ||
s(u, "*uimserv*") ||
s(u, "*ulukaris*") ||
s(u, "*umeng*") ||
s(u, "*upgulpinon*") ||
s(u, "*ushoofop*") ||
s(u, "*vermarktung*") ||
s(u, "*vibrantmedia*") ||
s(u, "*voodoo*") ||
s(u, "*vserv.mobi*") ||
s(u, "*wbidder.online*") ||
s(u, "*wct.link*") ||
s(u, "*webads*") ||
s(u, "*webcounter*") ||
s(u, "*webgains*") ||
s(u, "*webstat*") ||
s(u, "*xiti*") ||
s(u, "*xuossk3tu6hb*") ||
s(u, "*yads*") ||
s(u, "*yahoo*ads*") ||
s(u, "*yieldmanager*") ||
s(u, "*yieldmo*") ||
s(u, "*yoc.mobi*") ||
s(u, "*ythome*") ||
s(u, "*yumenetworks*") ||
s(u, "*zeroredirect*") ||
s(u, "*zestadz*") ||
s(u, "*zumobi*")) { 
		return "PROXY 8.8.8.8:53";
	}
	return PROXY_DIRECT;
}